## -*- encoding: utf-8 -*-
## This file (AddIntSameSign.online.sagetex.sage) was *autogenerated* from AddIntSameSign.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('AddIntSameSign.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
