## -*- encoding: utf-8 -*-
## This file (AddIntDiffSigns.sagetex.sage) was *autogenerated* from AddIntDiffSigns.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('AddIntDiffSigns', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
