## -*- encoding: utf-8 -*-
## This file (AddIntMoney.online.sagetex.sage) was *autogenerated* from AddIntMoney.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('AddIntMoney.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
