## -*- encoding: utf-8 -*-
## This file (FractionsSimplify.online.sagetex.sage) was *autogenerated* from FractionsSimplify.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('FractionsSimplify.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
