## -*- encoding: utf-8 -*-
## This file (SubtractIntKCC.sagetex.sage) was *autogenerated* from SubtractIntKCC.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('SubtractIntKCC', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
